anaxago_core:
    resource: "@AnaxagoCoreBundle/Resources/config/routing.yml"
    prefix:   /

login:
    path: /login
    defaults: { _controller: AnaxagoCoreBundle:Security:login }

logout:
    path: /logout

anaxago_core_registration:
    path: /register
    defaults: { _controller: AnaxagoCoreBundle:Security:registration }

invest:
    path: /invest
    defaults: { _controller: AnaxagoCoreBundle:Invest:invest }


api_projects:
    path: /api/projects
    defaults: { _controller: AnaxagoCoreBundle:API:projectsList }


api_userprojects:
  path: /api/userprojects
  defaults: { _controller: AnaxagoCoreBundle:API:userProjectList }

api_invest:
  path: /api/invest
  defaults: { _controller: AnaxagoCoreBundle:API:investAPI }