<?php

namespace Anaxago\CoreBundle\Repository;

/**
 * FundingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class FundingRepository  extends \Doctrine\ORM\EntityRepository
{

}